### ISSUE TITLE
Improve the testimonials & Trip Planner UI

### ISSUE THREAD

**Issue by MadhunishaBala** [apu52/Travel_Website#494] opened 2024-05-18 07:34 UTC
The UI of the testimonials and Trip Planner could be improved. So, can you please assign this to me **under GSSOC'24**?

**Testimonials**
We can add some comments, as well as pictures of those who have used this app, and maybe create a separate page for it. 

**Planner UI**
Make sure the destinations also appear in a drop-down box and make sure the UI is more attractive.

**Comment by vctigerrfab** [comment] 2024-05-19 11:09
I want to work on this project.Kindly assign this issue to me.

**Comment by Ghanshyam89** [comment] 2024-05-23 04:07
Hi ,

Please add some example screenshots to understand your issue.

Regards
Project Mentor (GSSoC' 24)

**Comment by MadhunishaBala** [comment] 2024-05-23 12:05
![image](https://github.com/apu52/Travel_Website/assets/127708789/22e1c5c6-25ce-4087-86c2-bdf6040e06ea)
In the planner page, we can see the destinations are not given, I understand it's a large scope but then the user might find it easier if the options do get shown, for him or her to select it easily and the UI of this page is a bit blank, I feel, so maybe I could add in a more eye pleasing background and change the format of the input part of the planner.

**Comment by apu52** [comment] 2024-05-26 13:34
@MadhunishaBala the issue is already exhausted . & the UI of the trip planner , testimonial page is already improved .so sorry to close this issue.
HAPPY CODING!!!!!!!!!!

**Closed by apu52** 2024-05-26 13:34 UTC
Labels: enhancement, question
