### ISSUE TITLE
Chatbot section styling

### ISSUE THREAD

**Issue by sujayx07** [apu52/Travel_Website#317] opened 2024-05-10 05:41 UTC
Chatbot section styling is not good at all

it should me more attractive and addictive after a good styling

![download](https://github.com/apu52/Travel_Website/assets/149602382/d956f77a-15b2-4b72-882d-6f9cc9f302d8)

***GSSOC'24***

**Comment by riyasaxena32** [comment] 2024-05-10 06:41
I will design chatbot section please assign this issue to me .i wanna contribute

**Comment by AmrutaJayanti** [comment] 2024-05-11 11:22
Can you please assign me this project under gssoc'2024 . I will design a chatbot section easy to handle any request .

**Comment by apu52** [comment] 2024-05-13 13:57
@SujayDeyTMSL Welcome to TRAVEL_WEBSITE.
thanks for raising the issue . The issue is good . 
Just I wanna ask if you can provide me some sample UI pics of chatbot you are proposing to change????????
So that I can Assign you this issue.

**Comment by apu52** [comment] 2024-05-13 13:59
@riyasaxena32 @AmrutaJayanti Thanks for commenting. But as per the rule of GSSOC'24 , I only can assign issues as first come first serve basis. So Try to raise a complete new issue on which you wan to work 
Thank you.

**Comment by Shatakshi-gupta-ggits** [comment] 2024-05-17 05:37
can you assign this issue to me . I wanna contribute.

**Comment by riyasaxena32** [comment] 2024-05-26 10:17
please assign this to me

**Comment by apu52** [comment] 2024-05-26 13:28
@SujayDeyTMSL are you still working on this issue ??

**Comment by riyasaxena32** [comment] 2024-05-28 10:25
please assign this to me

**Comment by DiwareNamrata23** [comment] 2024-06-03 19:07
I'm interested to style chatbot section in a better way . Please @apu52 sir assign this issue to me ..                                                 
Thank you!

**Comment by DakshantJain** [comment] 2024-06-14 12:52
Hello @apu52 

I loved your beautifully designed website! I noticed that the chatbot section where improvements could make it even more amazing. I'd be thrilled to help enhance its look and functionality for the best results.

Please consider assigning this task to me—I guarantee you'll be pleased with the outcome.

Thank you!

Best,
Dakshant Jain

**Comment by apu52** [comment] 2024-06-26 20:50
@riyasaxena32 I have assigned you .u can start working on this issue.

**Comment by riyasaxena32** [comment] 2024-07-03 19:19
ok

**Closed** 2024-12-28 15:18 UTC
Labels: bug, gssoc
