### ISSUE TITLE
hover effect

### ISSUE THREAD

**Issue by Ishmeetkaur36** [apu52/Travel_Website#1253] opened 2024-07-28 09:49 UTC
The red colored hover on header doesnt seems appealing. Changing its color would help

**Comment by apu52** [comment] 2024-07-29 06:59
@Ishmeetkaur36 the issue is not properly defined .please try to raise your issues properly with the help of the issue templates which are already present in the repo . Sorry to close this issue this time . But u can still make new issues

**Closed by apu52** 2024-07-29 06:59 UTC
