### ISSUE TITLE
Carousel Cards

### ISSUE THREAD

**Issue by adarsh0011** [apu52/Travel_Website#669] opened 2024-06-01 00:40 UTC
**Describe the bug**
The Content should be within the cards and the Testimonial & FAQ section need spacing for clean professional look. 

**Screenshots (Mandatory)**
![Screenshot (508)](https://github.com/apu52/Travel_Website/assets/113614601/a7ec0370-844d-4d47-bde8-abb7beab1d78)

**Additional Context (Mandatory )**
It can be resolved using box model.

***Are you contributing under any open-source program ?***
Gssoc'24

**Comment by KrishnenduDG** [comment] 2024-06-01 07:32
Hi @adarsh0011 , good observation and I also appreciate the logic of "Box model" for fixing it. However, when I am trying to reproduce it in my own system, it doesn't mimic the ss provided by you.

Anyways, can you specify the exact screen width and height for which the issue is occuring?

**Comment by adarsh0011** [comment] 2024-06-02 01:10
Hello @KrishnenduDG the issue is occurring for 1920 × 1080  screen size.

**Comment by Meeta-28** [comment] 2024-08-13 05:47
@apu52 please assign this issue to me

**Comment by Nikhilkumar111** [comment] 2024-10-01 17:36
Hello, Plz assign this issue to me.I  resolve this issue quickly .

**Closed** 2024-12-28 15:32 UTC
Labels: bug, question
