### ISSUE TITLE
media query addition in the contact us section

### ISSUE THREAD

**Issue by snehamalik09** [apu52/Travel_Website#333] opened 2024-05-10 12:09 UTC
Certainly. The issue at hand involves the "Contact Us" section of a web page overflowing onto the right side, likely disrupting the layout and functionality of the page. This overflow could be due to various reasons, such as improperly sized or positioned elements, excessive content, or CSS styling issues.
Please assign me the task of resolving the overflow issue in the "Contact Us" section so I can address it as part of my contribution to GSSOC 2024.
![contact](https://github.com/apu52/Travel_Website/assets/86192799/025947d0-07bd-430a-bc54-af10708dab43)

**Comment by Parishri07** [comment] 2024-05-10 15:10
I can resolve this issue of misalignment, please assign this task to me.

**Comment by Adiaparmar** [comment] 2024-05-10 15:11
Can i work on this issue for gssoc,24
I can resolve the issues with media queries and design of the page.

**Comment by Rohit153672** [comment] 2024-05-11 06:18
hello i want to solve this issue please assign me

**Comment by apu52** [comment] 2024-05-14 13:20
The issue is really good . But can you please raise this issue again more clearer (with issue templates)so that I can assign this to you @snehamalik09 
Sorry to close this issue for now

**Closed by apu52** 2024-05-14 13:20 UTC
Labels: bug
