### ISSUE TITLE
Feature_Request : Top destination slider

### ISSUE THREAD

**Issue by CoderKavyaG** [apu52/Travel_Website#38] opened 2024-01-15 04:25 UTC
**Is your feature request related to a problem? Please describe.**
In the Explore top destinations section of websites, there are arrow slide buttons that are not working and images aren't aligned that look cool in the website preview. 

**Describe the solution you'd like**
I will make the slide arrow buttons work by adding a slideshow of images having the same characteristics just images revolving in the section of 3 images and images will be of the same height and width increasing user impact over the website.

**Describe alternatives you've considered**
I have considered a slideshow of pics so new images can be added easily and they also look cool.

**Demo Video/Screenshot (Mandatory )**

https://github.com/apu52/Travel_Website/assets/147709304/a4d55f3e-03ac-44a2-a567-a1489a4c7598

![image](https://github.com/apu52/Travel_Website/assets/114172928/fb259176-201e-423d-915d-fae1171bcaab)

***Are you contributing under any open-source program ?***
Yes under JWOC I am contributing as mentee.

**Comment by apu52** [comment] 2024-01-15 04:37
@CoderKavyaG Welcome to the REPO
I will assign you 
But you are contributing under JWOC right??

**Comment by CoderKavyaG** [comment] 2024-01-15 05:08
Yes, I am!

**Comment by apu52** [comment] 2024-01-15 10:06
@CoderKavyaG You are assigned. You can start working on this issue.
You have 2-3 days to submit the PR.

**Comment by apu52** [comment] 2024-01-20 10:15
@CoderKavyaG are you still working on this issue. as this issue has already crossed the deadline. Sorry to unassign you.

**Comment by apu52** [comment] 2024-01-20 10:17
### The issue is open now to all of you.
If anyone want to work on this issue comment down. Whoever comments first with JWOC mentioned in it I will assign this issue to her/him

**Comment by Redclawww** [comment] 2024-01-20 11:56
Please assign me this issue under JWOC

**Comment by GhoshAditi** [comment] 2024-01-20 11:57
Please assign it to me under jwoc'24

**Comment by apu52** [comment] 2024-01-20 13:01
@Redclawww you are assigned. you can start working on this  issue. You just have 2-3 day s to complete this issue

**Comment by apu52** [comment] 2024-01-22 14:08
> Can you please assign me this issue under JWOC?

This issue is already assigned. you can raise new issue on which you want to work on

**Comment by antilneeraj** [comment] 2024-01-24 20:30
@apu52 As the assignee passed the 4 day limit and hasn't pushed any Pull Request.
Can you assign this issue to me under JWOC.

**Comment by Redclawww** [comment] 2024-01-25 03:13
I have been travelling for the past couple days can you just gimme today I'll get it done

**Comment by apu52** [comment] 2024-01-25 14:39
> I have been travelling for the past couple days can you just gimme today I'll get it done

Ok. you just have the time limit up to tonight otherwise I will be forced to unassign you

**Comment by apu52** [comment] 2024-01-27 10:38
> > I have been travelling for the past couple days can you just gimme today I'll get it done
> 
> Ok. you just have the time limit up to tonight otherwise I will be forced to unassign you @Redclawww

@Redclawww Where is your PR . sorry to unassign you

**Comment by apu52** [comment] 2024-01-27 10:39
@Jenis07 Can you work on this issue as per rule you will get the chance to contribute in this issue

**Comment by antilneeraj** [comment] 2024-01-27 11:49
@apu52 As the assignee passed the limit and hasn't pushed any Pull Request.

Please you assign this issue to me under JWOC.

**Comment by Sneha123-zudo** [comment] 2024-01-27 17:54
please assign me this issue under JWOC'24

**Comment by apu52** [comment] 2024-01-28 06:34
ok @antilneeraj You are assigned on this issue . You have 2-3 days to submit your PR. Happy Coding!!!!!

**Closed** 2024-01-29 13:31 UTC
Labels: enhancement, JWOC, Medium
