### ISSUE TITLE
Adding a section in website as how to maintain cleanliness in the areas people visit

### ISSUE THREAD

**Issue by Shreya-060304** [apu52/Travel_Website#331] opened 2024-05-10 11:14 UTC
People while travelling forget about not to make the place they go like hell. So if the website would contain necessary guidelines as what to follow while travelling would really help @arpanchowdhury53 Please assign me this project.

**Comment by hussain123sahil** [comment] 2024-05-10 12:59
I can solve this issue. Please assign me this issue.

**Comment by anvishelar** [comment] 2024-05-10 13:37
I am Anvi Shelar. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by apu52** [comment] 2024-05-14 13:15
@Shreya-060304 Please follow the issue templates to raise the issue & make it more clearer. as the issue is not clear to me
Sorry to close this issue

**Closed by apu52** 2024-05-14 13:15 UTC
