### ISSUE TITLE
I want to make the height of all pictures uniform for best trip package section.

### ISSUE THREAD

**Issue by saikatdey61** [apu52/Travel_Website#19] opened 2024-01-12 13:32 UTC
![WhatsApp Image 2024-01-12 at 19 01 45_d96cc207](https://github.com/apu52/Travel_Website/assets/128217785/5d0fad0f-6d66-4585-8573-1350b41c8cb6)

**Comment by saikatdey61** [comment] 2024-01-12 13:33
I want to work on this issue under jwoc 2024 , please assign me.

**Comment by saikatdey61** [comment] 2024-01-12 13:58
<img width="942" alt="image" src="https://github.com/apu52/Travel_Website/assets/128217785/c9eefbe3-7b05-4262-b1a4-9693782b4d46">

**Comment by rahat2134** [comment] 2024-01-13 06:41
This issue is a duplicate of #7.

**Comment by apu52** [comment] 2024-01-14 06:28
@saikatdey61 Welcome to the repo.
Sorry to close this issue.
Make sure to open the issues after coding period starts

**Closed by apu52** 2024-01-14 06:28 UTC
