### ISSUE TITLE
BUG nothing will show in their place of eiffel tower(card)

### ISSUE THREAD

**Issue by shuhaki** [apu52/Travel_Website#661] opened 2024-05-30 18:45 UTC
**Describe the bug**
a bluring show in the place of card option

**Expected behavior**

<img width="1355" alt="Screenshot 2024-05-31 at 12 08 14 AM" src="https://github.com/apu52/Travel_Website/assets/145912232/d7ea420a-3dc3-47cb-aa5c-012956b9bf2b">

**Additional Context (Mandatory )**

***Are you contributing under any open-source program ?***
GSSOC'24

**Comment by KrishnenduDG** [comment] 2024-06-01 07:36
Hi @shuhaki, I have tried reproducing this issue in my system but can't. I think due to a lil bit of lag in loading all the assets, the skeleton is loading and then it changes and that's OK I guess.

If you could provide a full video of the issue, it would be easier to proceed with it.

**Comment by apu52** [comment] 2024-06-07 04:00
@shuhaki this issue is already completed .  I am closing this issue but you can raise new issues on which you want to work on.

**Closed** 2024-06-07 04:00 UTC
Labels: wontfix
