### ISSUE TITLE
It is taking too much tym

### ISSUE THREAD

**Issue by tushargupta1504** [apu52/Travel_Website#201] opened 2024-01-27 15:27 UTC
The website is taking too much time to load

**Comment by apu52** [comment] 2024-01-28 06:25
@tushargupta1504 This is a very good issue but I will like to suggest you to please use proper issue templates to raise your issue 
![image](https://github.com/apu52/Travel_Website/assets/114172928/6c39fde7-d2b7-4005-8bbf-c1868b660942)

**Comment by apu52** [comment] 2024-01-28 06:25
The issue is still open just update your issue properly so that I can assign you this

**Comment by AftabMankapure** [comment] 2024-01-28 20:24
bro it happens because of css file and lots of Optimize Images in this project 
there are may css stm which are not used any where or some  same css stm are present in many files

**Comment by apu52** [comment] 2024-01-31 04:36
@tushargupta1504 are you working on this issue or I will close this issue

**Comment by tushargupta1504** [comment] 2024-01-31 04:49
Working

**Comment by apu52** [comment] 2024-02-01 06:28
> Working

In that Case, I am closing this issue , you must raise a new issue with proper issue template describing your issue

**Closed by apu52** 2024-02-01 06:28 UTC
Labels: bug, WAITING
