### ISSUE TITLE
misalignment in header - BUG

### ISSUE THREAD

**Issue by kairveeehh** [apu52/Travel_Website#307] opened 2024-05-09 13:49 UTC
would liek to give a cleaner Ui look to the site by aligning the header 
## please assign this issue to me under GSSoC'24 so that I can work on it
![Screenshot 2024-05-09 191727](https://github.com/apu52/Travel_Website/assets/145572028/59a27398-8a4d-45d5-b8ff-149d9a63895c)

**Comment by ritankarsaha** [comment] 2024-05-09 14:08
Assign this issue to me under GSSoc'24 so that i can work on it

**Comment by Gokilp** [comment] 2024-05-09 14:23
Assign this issue to me under GSSoc'24

**Comment by aditimishra0013** [comment] 2024-05-09 16:43
Assign this issue to me under GSSOC'24

**Comment by GarimaSingh0109** [comment] 2024-05-10 02:27
looking at one of the previous comment with picture of header & website in my laptop i think the navbar isn't responsive kindly assign me this issue I am willing to enhance the UI UX of the web-site

**Comment by Ankitapanda25** [comment] 2024-05-10 06:02
I have worked on loads of different kinds of navbar, I believe I can work on this. Kindly assign me this under GSSOC'24

**Comment by apu52** [comment] 2024-05-13 13:23
> would liek to give a cleaner Ui look to the site by aligning the header
> 
> ## please assign this issue to me under GSSoC'24 so that I can work on it
> ![Screenshot 2024-05-09 191727](https://private-user-images.githubusercontent.com/145572028/329267037-59a27398-8a4d-45d5-b8ff-149d9a63895c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU2MDY3NzksIm5iZiI6MTcxNTYwNjQ3OSwicGF0aCI6Ii8xNDU1NzIwMjgvMzI5MjY3MDM3LTU5YTI3Mzk4LThhNGQtNDVkNS1iOGZmLTE0OWQ5YTYzODk1Yy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxM1QxMzIxMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xYjQxODJkMDk1NzJiYjQ0ZGM3N2UxN2M5OWZhZWU3ZDU5MzRkZDdkZDY3MTc5NWI1NzA5MWJhOGNjNDRhNzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hT0NtrE8pqzlWrNLma4jPrB2XSxSeMzPssX6tDjwizg)

@kairveeehh Welcome to TRAVEL_WEBSITE. Thanks for raising the issue.
But the issue is not totally clear to me.
Can you please Raise a new issue using the ISSUE TEMPLATES already present there to raise the issue again ???

**Comment by apu52** [comment] 2024-05-13 13:24
![image](https://github.com/apu52/Travel_Website/assets/114172928/ee39f834-f0b2-4b87-abda-10998834384b)

Use this templates to raise your issue again
Sorry to close this issue . 
Happy Coding !!!!!!!!!!!!!

**Closed by apu52** 2024-05-13 13:24 UTC
Labels: bug
